name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Upload the virtual environment as an artifact
    - name: Upload virtual environment
      uses: actions/upload-artifact@v3
      with:
        name: venv
        path: venv

  tests:
    runs-on: ubuntu-latest
    needs: build  # Ensure that this job runs after the build job

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Download the virtual environment artifact
    - name: Download virtual environment
      uses: actions/download-artifact@v3
      with:
        name: venv
        path: venv

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  

    # Step 4: Run tests
    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest tests.web_crawler_test.TestWebCrawler
